# import streamlit as st 
# import requests
# import datetime
# import sys 
# BASE_URL = "http://127.0.0.1:8000"

# st.set_page_config(
#     page_title="Travel Planner Agentic Application",
#     page_icon="🌍",
#     layout="centered",
#     initial_sidebar_state="expanded"
# )
# st.title("🌍 Travel Planner Agentic Application")

# if "messages" not in st.session_state:
#     st.session_state.messages = []
    
# st.header("How can I assist you with your travel plans today? Let me know where you'd like to go or any specific preferences you have!")
# with st.form(key="travel_form",clear_on_submit=True):
#     user_input = st.text_input("User Input",placeholder="E.g., 'Plan a 5-day trip to Japan focusing on cultural experiences and local cuisine.'")
#     submit_button = st.form_submit_button(label="Submit")
    
#     if submit_button and user_input.strip():
#         try :
#             with st.spinner("Planning your trip..."):
#                 payload = {"question": user_input}
#                 response = requests.post(f"{BASE_URL}/query", json=payload)
#             if response.status_code != 200:
#                 answer = response.json().get("answer","")
#                 markdown_content=f""" # 🌍 AI Travel Plan

#                     # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
#                     # **Created by:** Atriyo's Travel Agent

#                     ---

#                     {answer}

#                     ---

#                     *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
#                         """
#                 st.markdown(markdown_content)
#             else:
#                 st.error(f"Error from server: {response.status_code} - {response.text}")
#         except Exception as e:
#             st.error(f"An error occurred: {str(e)}")
            
import streamlit as st
import requests
import datetime

BASE_URL = "http://127.0.0.1:8000"  # change to your deployed URL if needed

st.set_page_config(
    page_title="Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)
st.title("🌍 Travel Planner — Agentic Application")

if "messages" not in st.session_state:
    st.session_state.messages = []  # store tuples (user, bot, timestamp)

st.header(
    "How can I assist you with your travel plans today? "
    "Tell me where you'd like to go or any preferences (budget, activities, dates)."
)

with st.form(key="travel_form", clear_on_submit=True):
    user_input = st.text_input(
        "Your request",
        placeholder="E.g., Plan a 5-day trip to Japan focusing on culture and food.",
    )
    submit_button = st.form_submit_button(label="Submit")

if submit_button and user_input and user_input.strip():
    with st.spinner("Planning your trip..."):
        try:
            payload = {"question": user_input}
            resp = requests.post(f"{BASE_URL}/query", json=payload, timeout=30)

            if resp.ok:
                data = resp.json()
                # your FastAPI returns {"response": response_message}
                bot_answer = data.get("response") or data.get("error") or str(data)
                timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                st.session_state.messages.append((user_input, bot_answer, timestamp))

                # display nicely
                st.markdown(
                    f"""## 🌍 AI Travel Plan\n
**Generated:** {timestamp}  
**Created by:** Agentic Travel Planner

---

{bot_answer}

---

*This travel plan was generated by AI. Please verify all details (prices, hours, travel requirements) before booking.*"""
                )
            else:
                # non-2xx response
                try:
                    err = resp.json()
                except Exception:
                    err = resp.text
                st.error(f"Server error: {resp.status_code} — {err}")

        except requests.Timeout:
            st.error("Request timed out. Try again or increase the timeout.")
        except requests.RequestException as e:
            st.error(f"Network error: {e}")
        except Exception as e:
            st.error(f"An unexpected error occurred: {e}")

# show history (optional)
if st.session_state.messages:
    st.markdown("---")
    st.subheader("Conversation history")
    for user_msg, bot_msg, ts in reversed(st.session_state.messages[-10:]):
        st.markdown(f"**You** ({ts}): {user_msg}")
        st.markdown(f"**AI**: {bot_msg}")
        st.markdown("---")
